# Generated by Django 5.2.4 on 2025-07-07 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('store_performance', 'Store Performance Report'), ('product_analysis', 'Product Analysis Report'), ('customer_insights', 'Customer Insights Report'), ('market_trends', 'Market Trends Report'), ('competitive_analysis', 'Competitive Analysis Report'), ('financial_summary', 'Financial Summary Report')], max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('parameters', models.JSONField(blank=True, help_text='Additional report parameters and filters', null=True)),
                ('raw_data', models.JSONField(help_text='Raw aggregated data used in the report')),
                ('ai_summary_text', models.TextField(help_text='AI-generated narrative summary of key insights and trends')),
                ('visualizations', models.JSONField(blank=True, help_text='Chart and graph data for visualizations', null=True)),
                ('file_url', models.URLField(blank=True, help_text='URL to the generated report file (PDF, Excel, etc.)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.store')),
            ],
            options={
                'db_table': 'generated_reports',
                'indexes': [models.Index(fields=['generated_by', 'generated_at'], name='generated_r_generat_c8cc24_idx'), models.Index(fields=['store', 'report_type'], name='generated_r_store_i_accd75_idx'), models.Index(fields=['status'], name='generated_r_status_a41f66_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('store_performance', 'Store Performance Report'), ('product_analysis', 'Product Analysis Report'), ('customer_insights', 'Customer Insights Report'), ('market_trends', 'Market Trends Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('parameters', models.JSONField(blank=True, help_text='Report parameters and filters', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
                'indexes': [models.Index(fields=['user', 'is_active'], name='report_sche_user_id_cbff80_idx'), models.Index(fields=['next_run', 'is_active'], name='report_sche_next_ru_09abbf_idx')],
            },
        ),
    ]
