# Generated by Django 5.0.1 on 2025-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Raw aggregated data used in the report', null=True),
        ),
    ]
