# Generated by Django 5.0.1 on 2025-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_generatedreport_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='detailed_report_text',
            field=models.TextField(blank=True, help_text='Detailed narrative report with comprehensive analysis', null=True),
        ),
    ]
