# Generated by Django 5.0.1 on 2025-07-26 05:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (0-100) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='promotionusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotionusage',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='storediscountusage',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual discount amount applied for this store', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storediscountusage',
            name='store_cart_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Total amount for this store's items", max_digits=10),
        ),
    ]
