# Generated by Django 5.0.1 on 2025-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interaction_score',
            field=models.FloatField(default=0.0, help_text='Calculated score based on reviews, brand value, and interactions'),
        ),
        migrations.AddField(
            model_name='product',
            name='sentiment_rating',
            field=models.FloatField(default=0.0, help_text='Average sentiment score from reviews'),
        ),
    ]
