# Generated by Django 5.2.4 on 2025-07-07 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_criteria', models.JSONField(help_text='Criteria used for comparison (price, features, ratings, etc.)')),
                ('ai_analysis', models.JSONField(help_text='AI-generated comparison analysis and insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='comparisons', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_comparisons',
                'indexes': [models.Index(fields=['user', 'created_at'], name='product_com_user_id_9cc7de_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_type', models.CharField(choices=[('general', 'General Comparison'), ('category_specific', 'Category Specific'), ('price_analysis', 'Price Analysis'), ('service_quality', 'Service Quality')], max_length=50)),
                ('ai_insights', models.JSONField(help_text='AI-generated store comparison insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stores', models.ManyToManyField(related_name='comparisons', to='products.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_comparisons',
                'indexes': [models.Index(fields=['user', 'created_at'], name='store_compa_user_id_03b47c_idx')],
            },
        ),
    ]
