# Generated by Django 5.0.1 on 2025-07-26 05:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_when_added',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Product price when added to cart', max_digits=10),
        ),
    ]
