# Generated by Django 5.2.4 on 2025-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click'), ('add_to_cart', 'Add to Cart'), ('like', 'Like Product'), ('dislike', 'Dislike Product'), ('search', 'Search Query'), ('time_on_page', 'Time Spent on Page'), ('compare', 'Product Comparison'), ('share', 'Share Product')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context like search query, comparison criteria, time spent, etc.')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'user_behavior_logs',
            },
        ),
        migrations.CreateModel(
            name='UserSessionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('interaction_type', models.CharField(choices=[('view', 'Page View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('search', 'Search'), ('filter', 'Apply Filter'), ('sort', 'Sort Products')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('interaction_data', models.JSONField(blank=True, default=dict, help_text='Specific interaction data (search terms, filters applied, etc.)')),
            ],
            options={
                'db_table': 'user_session_interactions',
            },
        ),
        migrations.CreateModel(
            name='AIModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('recommendation', 'Recommendation Engine'), ('search', 'Search Enhancement'), ('sentiment', 'Sentiment Analysis'), ('comparison', 'Product Comparison'), ('personalization', 'Personalization')], max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall_score', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('successful_predictions', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, help_text='Average response time in milliseconds', null=True)),
                ('custom_metrics', models.JSONField(blank=True, default=dict, help_text='Model-specific performance metrics')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_model_performance',
                'indexes': [models.Index(fields=['model_type', 'evaluated_at'], name='ai_model_pe_model_t_97500b_idx'), models.Index(fields=['model_version'], name='ai_model_pe_model_v_264057_idx')],
            },
        ),
    ]
