# Generated by Django 5.2.4 on 2025-07-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_models', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorlog',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product involved in the action (null for non-product actions)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='userbehaviorlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for guest users)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersessioninteraction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='usersessioninteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['user', 'timestamp'], name='user_behavi_user_id_53dc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['product', 'action_type'], name='user_behavi_product_0d8b32_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['session_id', 'timestamp'], name='user_behavi_session_b604e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='user_behavi_action__e17d95_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessioninteraction',
            index=models.Index(fields=['session_id', 'timestamp'], name='user_sessio_session_eca3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessioninteraction',
            index=models.Index(fields=['user', 'timestamp'], name='user_sessio_user_id_984d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessioninteraction',
            index=models.Index(fields=['interaction_type', 'timestamp'], name='user_sessio_interac_15d833_idx'),
        ),
    ]
