version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: best_on_click_db
      POSTGRES_USER: best_on_click_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://best_on_click_user:your_secure_password@db:5432/best_on_click_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
